# Generated by Django 3.2.4 on 2021-06-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_user_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
    ]
